---
- name: Extra vars vault
  connection: local
  hosts: localhost
  gather_facts: no
  no_log: True
  # reference the encrypted variable file
  vars_files:
    - vars/oscreds.yml

  tasks:
    - name: print out encrypted vars
      ansible.builtin.debug:
        msg: "{{ imscloud }}"

